VERBOSE: True

MODEL:
  SESSION: 'UW'
  INPUT: 'input'
  TARGET: 'target'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4 
  NUM_EPOCHS: 200 
  LR_INITIAL: 2e-4 
  LR_MIN: 1e-6
  SEED: 3407 
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1 
  RESUME: False
  PS_W: 256 
  PS_H: 256 
  TRAIN_DIR: '../UW/train/' 
  VAL_DIR: '../UW/test/'    
  SAVE_DIR: './checkpoints/'     
  ORI: False 

TESTING:
  WEIGHT: './checkpoints/best.pth'
  SAVE_IMAGES: True 